#!/usr/bin/env python

import rospy
from std_msgs.msg import Int16MultiArray
from Tkinter import *

pub = rospy.Publisher('sliderData', Int16MultiArray, queue_size=20)
rospy.init_node('tkinterGUI', anonymous=True)

def publishData(junk):
	a = Int16MultiArray()
	a.data.append(var1.get())
	a.data.append(var2.get())
	a.data.append(var3.get())
	a.data.append(var4.get())
	a.data.append(var5.get())
	a.data.append(var6.get())
	a.data.append(var7.get())
	a.data.append(var8.get())
	a.data.append(var9.get())
	a.data.append(var10.get())
	a.data.append(var11.get())
	a.data.append(var12.get())
	pub.publish(a)
	# print a.data

root = Tk()
frame = Frame(root)
frame.pack()

topFrame = Frame(frame)
botFrame = Frame(frame)

topFrame.pack(side = TOP)
botFrame.pack(side = BOTTOM)

var1 = IntVar()
var2 = IntVar()
var3 = IntVar()
var4 = IntVar()
var5 = IntVar()
var6 = IntVar()
var7 = IntVar()
var8 = IntVar()
var9 = IntVar()
var10 = IntVar()
var11 = IntVar()
var12 = IntVar()

scale1 = Scale(topFrame, label = 'kPThrust', variable = var1, from_ = 0, to = 5, command = publishData)
scale1.set(0)
scale1.pack(side=LEFT)
scale2 = Scale(topFrame, label = 'kiThrust', variable = var2, from_ = 0, to = 5, command = publishData)
scale2.set(0)
scale2.pack(side=LEFT)
scale3 = Scale(topFrame, label = 'kdThrust', variable = var3, from_ = 0, to = 5, command = publishData)
scale3.set(0)
scale3.pack(side=LEFT)
scale4 = Scale(botFrame, label = 'kpRoll', variable = var4, from_ = 0, to = 5, command = publishData)
scale4.set(0)
scale4.pack(side = LEFT)
scale5 = Scale(botFrame, label = 'kiRoll', variable = var5, from_ = 0, to = 5, command = publishData)
scale5.set(0)
scale5.pack(side=LEFT)
scale6 = Scale(botFrame, label = 'kdRoll', variable = var6, from_ = 0, to = 5, command = publishData)
scale6.set(0)
scale6.pack(side=LEFT)
scale7 = Scale(topFrame, label = 'kpPitch', variable = var7, from_ = 0, to = 5, command = publishData)
scale7.set(0)
scale7.pack(side=LEFT)
scale8 = Scale(topFrame, label = 'kiPitch', variable = var8, from_ = 0, to = 5, command = publishData)
scale8.set(0)
scale8.pack(side=LEFT)
scale9 = Scale(topFrame, label = 'kdPitch', variable = var9, from_ = 0, to = 5, command = publishData)
scale9.set(0)
scale9.pack(side=LEFT)
scale10 = Scale(botFrame, label = 'kpYaw', variable = var10, from_ = 0, to = 5, command = publishData)
scale10.set(0)
scale10.pack(side = LEFT)
scale11 = Scale(botFrame, label = 'kiYaw', variable = var11, from_ = 0, to = 5, command = publishData)
scale11.set(0)
scale11.pack(side=LEFT)
scale12 = Scale(botFrame, label = 'kdYaw', variable = var12, from_ = 0, to = 5, command = publishData)
scale12.set(0)
scale12.pack(side=LEFT)

root.mainloop()